// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum BarcodeFormat: Int {
  case aztec = 0
  case codabar = 1
  case code39 = 2
  case code93 = 3
  case code128 = 4
  case dataMatrix = 5
  case ean8 = 6
  case ean13 = 7
  case pdf417 = 8
  case qrCode = 9
  case upcA = 10
  case upcE = 11
  case itf = 12
}

enum CameraLensDirection: Int {
  case front = 0
  case back = 1
  case ext = 2
  case unknown = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct CameraOpenResponse {
  var supportsFlash: Bool? = nil
  var height: Int64? = nil
  var width: Int64? = nil
  var textureId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CameraOpenResponse? {
    let supportsFlash: Bool? = nilOrValue(pigeonVar_list[0])
    let height: Int64? = nilOrValue(pigeonVar_list[1])
    let width: Int64? = nilOrValue(pigeonVar_list[2])
    let textureId: String? = nilOrValue(pigeonVar_list[3])

    return CameraOpenResponse(
      supportsFlash: supportsFlash,
      height: height,
      width: width,
      textureId: textureId
    )
  }
  func toList() -> [Any?] {
    return [
      supportsFlash,
      height,
      width,
      textureId,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DetectedBarcode {
  var rawValue: String? = nil
  var cornerPoints: [CornerPoint?]? = nil
  var format: BarcodeFormat? = nil
  var textValue: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DetectedBarcode? {
    let rawValue: String? = nilOrValue(pigeonVar_list[0])
    let cornerPoints: [CornerPoint?]? = nilOrValue(pigeonVar_list[1])
    let format: BarcodeFormat? = nilOrValue(pigeonVar_list[2])
    let textValue: String? = nilOrValue(pigeonVar_list[3])

    return DetectedBarcode(
      rawValue: rawValue,
      cornerPoints: cornerPoints,
      format: format,
      textValue: textValue
    )
  }
  func toList() -> [Any?] {
    return [
      rawValue,
      cornerPoints,
      format,
      textValue,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CornerPoint {
  var x: Double
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CornerPoint? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double

    return CornerPoint(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
}

private class PigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BarcodeFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraLensDirection(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return CameraOpenResponse.fromList(self.readValue() as! [Any?])
    case 132:
      return DetectedBarcode.fromList(self.readValue() as! [Any?])
    case 133:
      return CornerPoint.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BarcodeFormat {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraLensDirection {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraOpenResponse {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? DetectedBarcode {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? CornerPoint {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonPigeonCodecWriter(data: data)
  }
}

class PigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonPigeonCodec(readerWriter: PigeonPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BarcodeKitHostApi {
  func openCamera(direction: CameraLensDirection, formats: [Int64], fallbackDirections: [CameraLensDirection], completion: @escaping (Result<CameraOpenResponse, Error>) -> Void)
  func setOCREnabled(enabled: Bool) throws
  func closeCamera() throws
  func pauseCamera() throws
  func resumeCamera() throws
  func setTorch(enabled: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BarcodeKitHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `BarcodeKitHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BarcodeKitHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.openCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let directionArg = args[0] as! CameraLensDirection
        let formatsArg = args[1] as! [Int64]
        let fallbackDirectionsArg = args[2] as! [CameraLensDirection]
        api.openCamera(direction: directionArg, formats: formatsArg, fallbackDirections: fallbackDirectionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openCameraChannel.setMessageHandler(nil)
    }
    let setOCREnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.setOCREnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setOCREnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setOCREnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setOCREnabledChannel.setMessageHandler(nil)
    }
    let closeCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.closeCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeCameraChannel.setMessageHandler { _, reply in
        do {
          try api.closeCamera()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeCameraChannel.setMessageHandler(nil)
    }
    let pauseCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.pauseCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseCameraChannel.setMessageHandler { _, reply in
        do {
          try api.pauseCamera()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseCameraChannel.setMessageHandler(nil)
    }
    let resumeCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.resumeCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeCameraChannel.setMessageHandler { _, reply in
        do {
          try api.resumeCamera()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeCameraChannel.setMessageHandler(nil)
    }
    let setTorchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.setTorch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTorchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setTorch(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTorchChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BarcodeKitFlutterApiProtocol {
  /// Caleld from the host when a barcode is detected.
  func onBarcodeScanned(barcode barcodeArg: DetectedBarcode, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called from the host when text is detected.
  func onTextDetected(text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called from the host when the torch state changes.
  func onTorchStateChanged(enabled enabledArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BarcodeKitFlutterApi: BarcodeKitFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonPigeonCodec {
    return PigeonPigeonCodec.shared
  }
  /// Caleld from the host when a barcode is detected.
  func onBarcodeScanned(barcode barcodeArg: DetectedBarcode, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onBarcodeScanned\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([barcodeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called from the host when text is detected.
  func onTextDetected(text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onTextDetected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([textArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called from the host when the torch state changes.
  func onTorchStateChanged(enabled enabledArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onTorchStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([enabledArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
