// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum BarcodeFormat {
  aztec,
  codabar,
  code39,
  code93,
  code128,
  dataMatrix,
  ean8,
  ean13,
  pdf417,
  qrCode,
  upcA,
  upcE,
  itf,
}

enum CameraLensDirection {
  front,
  back,
  ext,
  unknown,
}

class CameraOpenResponse {
  CameraOpenResponse({
    this.supportsFlash,
    this.height,
    this.width,
    this.textureId,
  });

  bool? supportsFlash;

  int? height;

  int? width;

  String? textureId;

  Object encode() {
    return <Object?>[
      supportsFlash,
      height,
      width,
      textureId,
    ];
  }

  static CameraOpenResponse decode(Object result) {
    result as List<Object?>;
    return CameraOpenResponse(
      supportsFlash: result[0] as bool?,
      height: result[1] as int?,
      width: result[2] as int?,
      textureId: result[3] as String?,
    );
  }
}

class DetectedBarcode {
  DetectedBarcode({
    this.rawValue,
    this.cornerPoints,
    this.format,
    this.textValue,
  });

  String? rawValue;

  List<CornerPoint?>? cornerPoints;

  BarcodeFormat? format;

  String? textValue;

  Object encode() {
    return <Object?>[
      rawValue,
      cornerPoints,
      format,
      textValue,
    ];
  }

  static DetectedBarcode decode(Object result) {
    result as List<Object?>;
    return DetectedBarcode(
      rawValue: result[0] as String?,
      cornerPoints: (result[1] as List<Object?>?)?.cast<CornerPoint?>(),
      format: result[2] as BarcodeFormat?,
      textValue: result[3] as String?,
    );
  }
}

class CornerPoint {
  CornerPoint({
    required this.x,
    required this.y,
  });

  double x;

  double y;

  Object encode() {
    return <Object?>[
      x,
      y,
    ];
  }

  static CornerPoint decode(Object result) {
    result as List<Object?>;
    return CornerPoint(
      x: result[0]! as double,
      y: result[1]! as double,
    );
  }
}

/// A single recognized line of OCR text, with geometry mirroring
/// [DetectedBarcode] so both can be positioned/compared using the same
/// full camera-texture pixel coordinate space (post sensor-rotation,
/// "display" orientation, matching the width/height returned by
/// [BarcodeKitHostApi.openCamera]).
class DetectedText {
  DetectedText({
    required this.text,
    required this.confidence,
    required this.cornerPoints,
    required this.blockIndex,
    required this.lineIndex,
  });

  /// The recognized text content of this line.
  String text;

  /// Recognition confidence (0..1). On Android this is ML Kit's
  /// `Text.Line.getConfidence()`. On iOS this is
  /// `VNRecognizedText.confidence` for the top candidate.
  double confidence;

  /// The four corners of the line's bounding quadrilateral, in the same
  /// coordinate space as [DetectedBarcode.cornerPoints].
  List<CornerPoint?> cornerPoints;

  /// Groups lines belonging to the same OCR text block (ML Kit only).
  /// Always 0 on iOS, since Vision has no block concept - only individual
  /// line-level observations.
  int blockIndex;

  /// The line's order within its block (reading order).
  int lineIndex;

  Object encode() {
    return <Object?>[
      text,
      confidence,
      cornerPoints,
      blockIndex,
      lineIndex,
    ];
  }

  static DetectedText decode(Object result) {
    result as List<Object?>;
    return DetectedText(
      text: result[0]! as String,
      confidence: result[1]! as double,
      cornerPoints: (result[2] as List<Object?>?)!.cast<CornerPoint?>(),
      blockIndex: result[3]! as int,
      lineIndex: result[4]! as int,
    );
  }
}

/// A normalized (0..1) rectangular region of a camera frame, expressed in
/// the same "display" orientation as the width/height returned by
/// [BarcodeKitHostApi.openCamera] (i.e. already accounting for sensor
/// rotation, before any further widget-level rotation).
class MaskRegion {
  MaskRegion({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  });

  double left;

  double top;

  double right;

  double bottom;

  Object encode() {
    return <Object?>[
      left,
      top,
      right,
      bottom,
    ];
  }

  static MaskRegion decode(Object result) {
    result as List<Object?>;
    return MaskRegion(
      left: result[0]! as double,
      top: result[1]! as double,
      right: result[2]! as double,
      bottom: result[3]! as double,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BarcodeFormat) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is CameraLensDirection) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is CameraOpenResponse) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is DetectedBarcode) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is CornerPoint) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is DetectedText) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is MaskRegion) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : BarcodeFormat.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CameraLensDirection.values[value];
      case 131: 
        return CameraOpenResponse.decode(readValue(buffer)!);
      case 132: 
        return DetectedBarcode.decode(readValue(buffer)!);
      case 133: 
        return CornerPoint.decode(readValue(buffer)!);
      case 134: 
        return DetectedText.decode(readValue(buffer)!);
      case 135: 
        return MaskRegion.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BarcodeKitHostApi {
  /// Constructor for [BarcodeKitHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BarcodeKitHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CameraOpenResponse> openCamera(CameraLensDirection direction, List<int> formats, List<CameraLensDirection> fallbackDirections) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.openCamera$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[direction, formats, fallbackDirections]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CameraOpenResponse?)!;
    }
  }

  Future<void> setOCREnabled(bool enabled) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.setOCREnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Restricts both barcode detection and OCR (when enabled) to [region] of
  /// the camera frame instead of scanning the entire frame, matching the
  /// visible mask cutout. Android only for now.
  Future<void> setMaskRegion(MaskRegion region) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.setMaskRegion$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[region]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Discards recognized text lines whose confidence score is below
  /// [minConfidence] (0..1) before forwarding them via
  /// `BarcodeKitFlutterApi.onTextDetected`. Defaults to 0 (no filtering) if
  /// never called.
  Future<void> setMinTextConfidence(double minConfidence) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.setMinTextConfidence$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[minConfidence]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> closeCamera() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.closeCamera$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> pauseCamera() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.pauseCamera$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> resumeCamera() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.resumeCamera$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setTorch(bool enabled) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.setTorch$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class BarcodeKitFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Caleld from the host when a barcode is detected.
  void onBarcodeScanned(DetectedBarcode barcode);

  /// Called from the host when a line of text is detected.
  void onTextDetected(DetectedText detectedText);

  /// Called from the host when the torch state changes.
  void onTorchStateChanged(bool enabled);

  static void setUp(BarcodeKitFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onBarcodeScanned$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onBarcodeScanned was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DetectedBarcode? arg_barcode = (args[0] as DetectedBarcode?);
          assert(arg_barcode != null,
              'Argument for dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onBarcodeScanned was null, expected non-null DetectedBarcode.');
          try {
            api.onBarcodeScanned(arg_barcode!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onTextDetected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onTextDetected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DetectedText? arg_detectedText = (args[0] as DetectedText?);
          assert(arg_detectedText != null,
              'Argument for dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onTextDetected was null, expected non-null DetectedText.');
          try {
            api.onTextDetected(arg_detectedText!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onTorchStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onTorchStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_enabled = (args[0] as bool?);
          assert(arg_enabled != null,
              'Argument for dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onTorchStateChanged was null, expected non-null bool.');
          try {
            api.onTorchStateChanged(arg_enabled!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
