// Autogenerated from Pigeon (v24.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class BarcodeFormat(val raw: Int) {
  AZTEC(0),
  CODABAR(1),
  CODE39(2),
  CODE93(3),
  CODE128(4),
  DATA_MATRIX(5),
  EAN8(6),
  EAN13(7),
  PDF417(8),
  QR_CODE(9),
  UPC_A(10),
  UPC_E(11),
  ITF(12);

  companion object {
    fun ofRaw(raw: Int): BarcodeFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CameraLensDirection(val raw: Int) {
  FRONT(0),
  BACK(1),
  EXT(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): CameraLensDirection? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CameraOpenResponse (
  val supportsFlash: Boolean? = null,
  val height: Long? = null,
  val width: Long? = null,
  val textureId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraOpenResponse {
      val supportsFlash = pigeonVar_list[0] as Boolean?
      val height = pigeonVar_list[1] as Long?
      val width = pigeonVar_list[2] as Long?
      val textureId = pigeonVar_list[3] as String?
      return CameraOpenResponse(supportsFlash, height, width, textureId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supportsFlash,
      height,
      width,
      textureId,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DetectedBarcode (
  val rawValue: String? = null,
  val cornerPoints: List<CornerPoint?>? = null,
  val format: BarcodeFormat? = null,
  val textValue: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DetectedBarcode {
      val rawValue = pigeonVar_list[0] as String?
      val cornerPoints = pigeonVar_list[1] as List<CornerPoint?>?
      val format = pigeonVar_list[2] as BarcodeFormat?
      val textValue = pigeonVar_list[3] as String?
      return DetectedBarcode(rawValue, cornerPoints, format, textValue)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rawValue,
      cornerPoints,
      format,
      textValue,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CornerPoint (
  val x: Double,
  val y: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CornerPoint {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      return CornerPoint(x, y)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
    )
  }
}
private open class PigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BarcodeFormat.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraLensDirection.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraOpenResponse.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DetectedBarcode.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CornerPoint.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BarcodeFormat -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is CameraLensDirection -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is CameraOpenResponse -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is DetectedBarcode -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is CornerPoint -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BarcodeKitHostApi {
  fun openCamera(direction: CameraLensDirection, formats: List<Long>, callback: (Result<CameraOpenResponse>) -> Unit)
  fun setOCREnabled(enabled: Boolean)
  fun closeCamera()
  fun pauseCamera()
  fun resumeCamera()
  fun setTorch(enabled: Boolean)

  companion object {
    /** The codec used by BarcodeKitHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `BarcodeKitHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BarcodeKitHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.openCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val directionArg = args[0] as CameraLensDirection
            val formatsArg = args[1] as List<Long>
            api.openCamera(directionArg, formatsArg) { result: Result<CameraOpenResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.setOCREnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setOCREnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.closeCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.closeCamera()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.pauseCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pauseCamera()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.resumeCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resumeCamera()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitHostApi.setTorch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setTorch(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class BarcodeKitFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by BarcodeKitFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
  }
  /** Caleld from the host when a barcode is detected. */
  fun onBarcodeScanned(barcodeArg: DetectedBarcode, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onBarcodeScanned$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(barcodeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Called from the host when text is detected. */
  fun onTextDetected(textArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onTextDetected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(textArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Called from the host when the torch state changes. */
  fun onTorchStateChanged(enabledArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mtrust_barcode_kit.BarcodeKitFlutterApi.onTorchStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(enabledArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
