name: Main - 🚀 build package

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    uses: ./.github/workflows/build_workflow.yaml
    with:
      branch: main
      pre_release: false
      app_id: ${{ vars.BUMPER_APP_ID }}
    secrets:
      app_private_key: ${{ secrets.BUMPER_APP_KEY }}
